# Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# Split
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Питание
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000
CONFIG_ZMK_EXT_POWER=n

# Включение трекбола PMW3610
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610_ALT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y

# Совместимость со старыми названиями настроек для драйвера PMW3610
CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=30000
CONFIG_PMW3610_REST2_RUN_TIME_MS=30000
CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=30000
CONFIG_PMW3610_REST1_RUN_TIME_MS=30000
