# Базовая конфигурация для Charybdis
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_EXT_POWER=n
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Включаем трекбол
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610_ALT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
